export const answers = [
  "Yes",
  "No",
  "Maybe",
  "Definitely",
  "I'm not sure",
  "Of course",
  "Certainly",
  "Absolutely",
  "Not a chance",
  "Ask again later",
  "Outlook not so good",
  "Signs point to yes",
  "You can count on it",
  "It is certain",
  "Without a doubt",
  "Reply hazy, try again",
  "My sources say no",
  "Cannot predict now",
  "Concentrate and ask again",
  "Better not tell you now",
  "Very doubtful",
  "As I see it, yes",
  "Don't count on it",
  "Most likely",
  "All signs point to no",
  "Very likely",
  "The stars say yes",
  "The stars say no",
  "Absolutely not",
  "Absolutely yes",
  "In your dreams",
  "Not in a million years",
  "Absolutely positively",
  "Highly unlikely",
  "Highly likely",
  "It's a mystery",
  "I have my doubts",
  "Certainly not",
  "Certainly yes",
  "The answer is unclear",
  "The answer is obvious",
  "In your favor",
  "Not in your favor",
  "Ask someone else",
  "No way",
  "Possibly",
  "Definitely maybe",
  "Without a doubt",
  "Definitely not",
  "Definitely yes",
  "It's a possibility",
  "It's unlikely",
  "It's very likely",
  "It's improbable",
  "The outlook is positive",
  "The outlook is negative",
  "Try again tomorrow",
  "Chances are slim",
  "Chances are good",
  "I'm leaning towards yes",
  "I'm leaning towards no",
  "I'm on the fence",
  "I'm undecided",
  "It's a toss-up",
  "In your best interest",
  "Against your best interest",
  "The choice is yours",
  "You decide",
  "You have the power",
  "It's not up to you",
  "It's up to fate",
  "The ball is in your court",
  "It's in the cards",
  "It's written in the stars",
  "It's up to destiny",
  "It's up to chance",
  "It's a gamble",
  "It's a sure thing",
  "It's a long shot",
  "It's a win-win",
  "It's a lose-lose",
  "It's all or nothing",
  "The answer is within you",
  "The answer is outside you",
  "You hold the key",
  "You don't hold the key",
  "It's a test of your intuition",
  "It's a test of your luck",
  "The future is uncertain",
  "The future is clear",
  "Believe in yourself",
  "Don't believe in yourself",
  "Trust your instincts",
  "Don't trust your instincts",
  "Listen to your heart",
  "Don't listen to your heart",
  "The odds are in your favor",
  "The odds are against you",
  "Take a chance",
  "Play it safe",
  "Follow your dreams",
  "Forget your dreams",
  "Follow the signs",
  "Ignore the signs",
  "Take a leap of faith",
  "Stay in your comfort zone",
  "It's all in your mind",
  "It's out of your control",
  "The answer is in the question",
  "The answer is beyond the question",
  "Trust the process",
  "Question the process",
  "It's a journey",
  "It's a destination",
  "Everything happens for a reason",
  "Everything is random",
  "The universe has a plan",
  "The universe is chaotic",
];


export const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
  "Why was the math book sad? Because it had too many problems.",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't oysters donate to charity? Because they are shellfish.",
  "How does a penguin build its house? Igloos it together!",
  "What did one wall say to the other wall? 'I'll meet you at the corner!'",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I'm on a whiskey diet. I've lost three days already.",
  "I couldn't figure out how to put my seatbelt on. Then it 'clicked'!",
  "I used to be a baker, but I couldn't make enough dough.",
  "I'm reading a book on anti-gravity. It's impossible to put down.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What did the janitor say when he jumped out of the closet? 'Supplies!'",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why don't seagulls fly over the bay? Because then they'd be bagels!",
  "I'm friends with all electricians. We have great current connections.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "How do you organize a space party? You 'planet'!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I'm on a whiskey diet. I've lost three days already.",
  "I couldn't figure out how to put my seatbelt on. Then it 'clicked'!",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I'm friends with all electricians. We have great current connections.",
  "Why don't seagulls fly over the bay? Because then they'd be bagels!",
  "What did one wall say to the other wall? 'I'll meet you at the corner!'",
  "What do you call a fish with no eyes? Fsh!",
  "I'm reading a book on anti-gravity. It's impossible to put down.",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I'm friends with all electricians. We have great current connections.",
  "Why don't seagulls fly over the bay? Because then they'd be bagels!",
  "I'm on a whiskey diet. I've lost three days already.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "How does a penguin build its house? Igloos it together!",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What did one wall say to the other wall? 'I'll meet you at the corner!'",
];


export const facts = [
  "Honey never spoils. Archaeologists have even found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The world's oldest known recipe is a recipe for beer.",
  "Bananas are berries, but strawberries aren't.",
  "Cows have best friends and can become stressed when they are separated from them.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. It lasted for just 38 minutes.",
  "Octopuses have three hearts.",
  "Hippopotamus milk is pink.",
  "A group of flamingos is called a 'flamboyance.'",
  "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of the iron in the heat.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "The dot over the lowercase 'i' and 'j' is called a 'tittle.'",
  "In Switzerland, it is illegal to own just one guinea pig because they are prone to loneliness.",
  "Polar bears' skin is black, and their fur is not actually white but translucent.",
  "The largest desert in the world is not the Sahara but Antarctica.",
  "A day on Venus is longer than a year on Venus. It rotates on its axis incredibly slowly.",
  "In the 16th century, Turkish women could initiate a divorce if their husbands didn't provide enough coffee.",
  "The unicorn is the national animal of Scotland.",
  "The smell of freshly-cut grass is actually a plant distress call.",
  "A day on Mercury is longer than its year.",
  "The original name for the search engine Google was 'Backrub.'",
  "Cleopatra was Greek, not Egyptian.",
  "The state of Florida is larger than England.",
  "Banging your head against a wall burns 150 calories per hour.",
  "A single strand of spaghetti is called a 'spaghetto.'",
  "A group of owls is called a 'parliament.'",
  "There are more possible iterations of a game of chess than there are atoms in the observable universe.",
  "The longest word in the English language without a vowel is 'rhythms.'",
  "The human brain is more active during sleep than during the day while awake.",
  "There are more possible iterations of a game of chess than there are atoms in the observable universe.",
  "The longest word in the English language without a vowel is 'rhythms.'",
  "The human brain is more active during sleep than during the day while awake.",
  "The world's largest desert is Antarctica.",
  "Hawaii is moving toward Japan at the rate of almost 4 inches per year.",
  "The longest time between two twins being born is 87 days.",
  "The moon has moonquakes.",
  "The first recorded game of baseball was played in 1846 in Hoboken, New Jersey.",
  "Bananas are berries, but strawberries are not.",
  "A day on Venus is longer than a year on Venus.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. It lasted for just 38 minutes.",
  "The Great Wall of China is not visible from space without aid.",
  "Cows have best friends and can become stressed when they are separated from them.",
  "Octopuses have three hearts.",
  "A group of flamingos is called a 'flamboyance.'",
  "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of the iron in the heat.",
  "Hippopotamus milk is pink.",
  "A day on Venus is longer than a year on Venus.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. It lasted for just 38 minutes.",
  "Bananas are berries, but strawberries are not.",
  "Honey never spoils. Archaeologists have even found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
];








